version: "3"
services:
  app:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - /home/node/short-url-with-token-service/node_modules
      - .:/home/node/short-url-with-token-service:cached
